export {
    loginConstants,
    employeeConstants,
    notificationActionType
}

const loginConstants = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

const employeeConstants = {
    EMP_LIST_LOAD_SUCCESS: 'EMP_LIST_LOAD_SUCCESS',
    EMP_LIST_LOAD_FAILURE: 'EMP_LIST_LOAD_FAILURE',
    EMP_DETAILS_LOAD_SUCCESS: 'EMP_DETAILS_LOAD_SUCCESS',
    EMP_DETAILS_LOAD_FAILURE: 'EMP_DETAILS_LOAD_FAILURE',
    EMP_SAVE_SUCCESS: 'EMP_SAVE_SUCCESS',
    EMP_SAVE_FAILURE: 'EMP_SAVE_FAILURE',
    EMP_DELETE_SUCCESS: 'EMP_DELETE_SUCCESS',
    EMP_DELETE_FAILURE: 'EMP_DELETE_FAILURE'
}

const notificationActionType = {
    NOTIFY_SUCCESS: 'NOTIFY_SUCCESS',
    NOTIFY_FAILURE: 'NOTIFY_FAILURE',
    CLOSE_NOTIFY: 'CLOSE_NOTIFY'
}